package ug.ktomczyk.techut.zad02.service;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import ug.ktomczyk.techut.zad02.domain.Phone;

public class PhoneService implements PhoneManager {

	private final String URL = "jdbc:hsqldb:hsql://localhost/workdb";
    private final Connection connection;
    private final Statement statement;
    private final String CREATE_TABLE_SQL = "CREATE TABLE Phone (id bigint GENERATED BY DEFAULT AS IDENTITY, producer VARCHAR(30) UNIQUE, price DOUBLE, productionDate DATE, isReserved BOOLEAN)";
    private boolean tableExists = false;
    
    private PreparedStatement addPhoneStmt;
    private PreparedStatement getAllPhonesStmt;
    private PreparedStatement getPhoneByIdStmt;
    private PreparedStatement deleteAllPhonesStmt;
    private PreparedStatement deletePhoneByIdStmt;
    private PreparedStatement getPhonesCheaperThanStmt;

    public PhoneService() throws SQLException {
        connection = DriverManager.getConnection(URL);
        statement = connection.createStatement();

        ResultSet rs = connection.getMetaData().getTables(null, null, null, null);

        while (rs.next()) {
            if ("Phone".equalsIgnoreCase(rs.getString("table_name"))) {
                tableExists = true;
                break;
            }
        }

        if (!tableExists) {
            statement.executeUpdate(CREATE_TABLE_SQL);
        }
        
        addPhoneStmt = connection.prepareStatement("INSERT INTO Phone (producer, price, productionDate, isReserved) VALUES (?,?,?,?)");
        getAllPhonesStmt = connection.prepareStatement("SELECT * FROM Phone");
        getPhonesCheaperThanStmt = connection.prepareStatement("SELECT * FROM Phone WHERE PRICE < ?");
        getPhoneByIdStmt = connection.prepareStatement("SELECT * FROM Phone WHERE ID=?");
        deleteAllPhonesStmt = connection.prepareStatement("DELETE FROM Phone");
        deletePhoneByIdStmt = connection.prepareStatement("DELETE FROM Phone WHERE ID=?");
    }
    
    public void addPhone(Phone phone) {
    	try {
    		addPhoneStmt.setString(1, phone.getProducer());
    		addPhoneStmt.setDouble(2, phone.getPrice());
    		addPhoneStmt.setDate(3, phone.getProductionDate());
    		addPhoneStmt.setBoolean(4, phone.isReserved());
    		
    		addPhoneStmt.executeUpdate();
    	}
    	catch (SQLException e) {
    		e.printStackTrace();
    	}
    }
    
    public List<Phone> getAllPhones() {
    	List<Phone> phones = new ArrayList<Phone>();
    	try {
    		ResultSet rs = getAllPhonesStmt.executeQuery();
    		
    		while (rs.next() ) {
    			Phone newPhone = new Phone(rs.getString("producer"),
    					rs.getDouble("price"), rs.getDate("productionDate"), rs.getBoolean("isReserved"));
    			phones.add(newPhone);
    		}
    	}
    	catch (SQLException e) {
    		e.printStackTrace();
    	}
    	
    	return phones;
    }
    
    public Phone getPhoneById(int id) {
		Phone newPhone = new Phone();
    	try {
    		getPhoneByIdStmt.setInt(1, id);
    		ResultSet rs = getPhoneByIdStmt.executeQuery();
    		
    		while (rs.next()) {
    			newPhone = new Phone(rs.getString("producer"),
    					rs.getDouble("price"), rs.getDate("productionDate"), rs.getBoolean("isReserved"));
    		}
    	}
    	catch (SQLException e) {
    		e.printStackTrace();
    	}
    	
    	return newPhone;
    }
    
    public void deleteAllPhones() {
    	try {
    		deleteAllPhonesStmt.executeUpdate();
    	}
    	catch (SQLException e) {
    		e.printStackTrace();
    	}
    }
    
    public void deletePhoneById(int id) {
    	try {
    		deletePhoneByIdStmt.setInt(1, id);
    		deletePhoneByIdStmt.executeUpdate();
    	}
    	catch (SQLException e) {
    		e.printStackTrace();
    	}
}

	@Override
	public boolean addPhones(List<Phone> phones) {
		try {
            connection.setAutoCommit(false);

            for (Phone phone : phones) {
            	addPhoneStmt.setString(1, phone.getProducer());
        		addPhoneStmt.setDouble(2, phone.getPrice());
        		addPhoneStmt.setDate(3, phone.getProductionDate());
        		addPhoneStmt.setBoolean(4, phone.isReserved());

        		addPhoneStmt.executeUpdate();
            }

            connection.commit();

            return true;
        } catch (SQLException e) {
            System.out.println("Rollback");
            try {
                connection.rollback();
            } catch (SQLException e1) {
                e1.printStackTrace();
            }
        }

        return false;
    }

	@Override
	public List<Phone> getPhonesCheaperThan(double price) {
		List<Phone> phones = new ArrayList<Phone>();
    	try {
    		getPhonesCheaperThanStmt.setDouble(1, price);
    		ResultSet rs = getPhonesCheaperThanStmt.executeQuery();
    		
    		while (rs.next() ) {
    			Phone newPhone = new Phone(rs.getString("producer"),
    					rs.getDouble("price"), rs.getDate("productionDate"), rs.getBoolean("isReserved"));
    			phones.add(newPhone);
    		}
    	}
    	catch (SQLException e) {
    		e.printStackTrace();
    	}
    	
    	return phones;
	}
}

